version: "3.9"

services:
  flask_app:
    restart: "always"
    container_name: "flask_app"
    depends_on:
      - db
    build:
      dockerfile: app_dockerfile/Dockerfile
      context: .
    expose:
      - "5000"

  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - "5432"

  nginx:
    image: nginx
    depends_on:
      - flask_app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  db-data:

